### ISSUE TITLE
Reflect.getMetadata is not a function  in Jest after updating to 2.8.1

### ISSUE THREAD

**Issue by ajwootto** [cloudflare/miniflare#415]
Our project heavily relies on using the metadata methods added to the global reflect object by the [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) package. These methods are used to power class decorators that are used by libraries like [class-validator](https://www.npmjs.com/package/class-validator) which we use for incoming data validation in our workers.

Starting from Miniflare 2.8.0, it seems that something was changed with how the global scope is handled in the `jest` test environment that breaks the `reflect-metadata` package's ability to add methods to the global `Reflect` object. Normally just by doing `import 'reflect-metadata'` these methods become available. However, after the Miniflare update our tests started failing with a `Reflect.getMetadata is not a function` error. 

Is there some new strategy for how Miniflare handles globals that might be conflicting with the `reflect-metadata` package's method for monkeypatching the Reflect object?

**Comment by mrbbot** [comment]
Hey! 👋 Apologies for the delayed reply. I've been focusing on Miniflare 3 for the past few weeks. I'm not too sure what's going on here. Have you got the same versions for `miniflare` and `jest-environment-miniflare`? Any chance your repo is open-source, or you can make a minimal-reproduction?

**Comment by penalosa** [comment]
Hey! Thanks for raising this issue! I'm going to close it for now since we haven't heard from you in a while, but if there's still outstanding questions feel free to comment with a minimal reproduction and we can open it again and investigate further.
