### ISSUE TITLE
v2.8.0: Error: Cannot find module '@miniflare/queues'

### ISSUE THREAD

**Issue by AlCalzone** [cloudflare/miniflare#360]
After upgrading to 2.8.0, miniflare doesn't start anymore. The requested module is nowhere to be found on disk, might be a missing dependency?
